name: dbt

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 20 * * *'

env:
  DBT_PROFILES_DIR: ./

  # https://docs.github.com/en/actions/security-guides/encrypted-secrets  
  PRD_SNOWFLAKE_ACCOUNT: ${{ secrets.PRD_SNOWFLAKE_ACCOUNT }}
  PRD_SNOWFLAKE_USER: ${{ secrets.PRD_SNOWFLAKE_USER }}
  PRD_SNOWFLAKE_PASSWORD: ${{ secrets.PRD_SNOWFLAKE_PASSWORD }}
  PRD_SNOWFLAKE_ROLE: ${{ secrets.PRD_SNOWFLAKE_ROLE }}
  PRD_SNOWFLAKE_WAREHOUSE: ${{ secrets.PRD_SNOWFLAKE_WAREHOUSE }}

jobs:
  dbt:
    name: dbt
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dbt
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: Install dependencies
        run: |
          pip install dbt-core dbt-snowflake
          dbt deps --target prod
      
      - name: Run dbt models
        run: dbt run --target prod -m tag:nightly

      - name: Test dbt models
        run: dbt test --target prod -m tag:nightly